name: Terraform Githug Actions
on: 
 push:
  branches: [master]
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout Code
     uses: actions/checkout@v2
   - name: AWS Credentials
     uses: aws-actions/configure-aws-credentials@v1
     with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
   - name: Terraform init
     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     run:  |
       echo "Hello"
       pwd
       ls
       cd vpc 
       pwd
       terraform init
       ls
   - name: Terraform plan
     env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     run:  |
       pwd
       cd vpc
       terraform plan
